Error | notauth:: | 01/07/2019 09:25:28:2528 | 9 | com.cpp.calypso.framework.ManejadorExcepciones | Excepcion: | HandleAbpExceptionEventHandler.HandleEvent => ManejadorExcepciones.HandleException => NLogLogger.Error | An error occurred while updating the entries. See the inner exception for details. | !
Error | notauth:: | 01/07/2019 09:26:39:2639 | 21 | com.cpp.calypso.framework.ManejadorExcepciones | Excepcion: | HandleAbpExceptionEventHandler.HandleEvent => ManejadorExcepciones.HandleException => NLogLogger.Error | An error occurred while updating the entries. See the inner exception for details. | !
Error | notauth:: | 01/07/2019 09:27:38:2738 | 36 | com.cpp.calypso.framework.ManejadorExcepciones | Excepcion: | HandleAbpExceptionEventHandler.HandleEvent => ManejadorExcepciones.HandleException => NLogLogger.Error | An error occurred while updating the entries. See the inner exception for details. | !
Error | notauth:: | 01/07/2019 09:29:31:2931 | 10 | com.cpp.calypso.framework.ManejadorExcepciones | Excepcion: | HandleAbpExceptionEventHandler.HandleEvent => ManejadorExcepciones.HandleException => NLogLogger.Error | An error occurred while updating the entries. See the inner exception for details. | !
